### ISSUE TITLE
Day 1 - In Class Challenge

### ISSUE THREAD

**Issue by BlackCubes** [dannysanchez559/2021_React_Apprenticeship#8]
**Is your feature request related to a problem? Please describe.**
None whatsoever.

**Describe the solution you'd like**
1. Write an arrow function called getMoviesByName that takes a string as input and uses fetch and async/await to get an array of movies with a matching title from OMDb API.
2. Write another arrow function called getMovieDetailsById that takes a valid OMDb movie id as input and uses fetch and async/await to get an object of detailed information about the specified movie.

**Comment by JayDampitan** [comment]
Lets try it out1
